name: onnx_translation
description: A Flutter package for ONNX-based translation models with tokenizer support.
version: 0.1.0
homepage: https://github.com/Adi-VI/onnx_translation
repository: https://github.com/Adi-VI/onnx_translation
license: MIT

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  onnxruntime: ^1.4.1
  ffi: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  # This package does not bundle assets itself; model assets
  # are expected to be provided by the user app.

  # If you want to add package-specific assets in future,
  # uncomment and add them here:
  # assets:
  #   - assets/your_asset_folder/

  # If you add custom fonts later, add here:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
